apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ocp-capv-webhook-cert
spec:
  ports:
    - port: 443
      targetPort: webhook-server