# Openshift specific https://github.com/openshift/service-ca-operator
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
